const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({

    username:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
    },
    role:{
        type:String,
        required:true,
        enum:["user","admin"],
        default:"user"
    },
    password:{
        type:String,
        required:true
    },
    lastLogin:{
        type:Date,
        default:Date.now()
    },
    accountLevel:{
        type:String,
        enum:["Bronze","Silver","Gold"],
        default:"Bronze"
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    profileImage:
    {
        type:String,
        default:""
    },
    coverImage:
    {
        type:String,
        default:""
    },
    Bio:{
        type:String,
        default:""
    },
    location:
    {
        type:String,
        default:""
    },
    noficationType:{
        email:{
            type:String,
            required:true,
        }
    },
    gender:{
        type:"String",
        enum:["male","female","other"],
    },
    profileViewers:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    ],
    followers:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    ],
    following:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    ],
    blockedUsers:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
    }],
    posts:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Post"
    }],
    likedPosts:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
    }],
    passwordResetToken:{
        type:String
    },
    passwordResetExpires:
    {
        type:Date
    },
    accountVerificationToken:
    {
        type:"String"
    },
    accountVerificationExpires:{
        type:Date
    }
},
{
    timestamps:true
});

module.exports = mongoose.model("User",userSchema);